# Script for figuring out how to equally weight data from different subjects

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [40]:
#bro=pd.read_html('http://epilepsiae.uniklinik-freiburg.de/patients/FR_253')
bro=pd.read_html('/Users/davidgroppe/Downloads/pat_FR_253.html')

In [42]:
len(bro)

6

In [45]:
bro[2]
#1 are clinical szrs
#2 are subclinical szrs

         #                      onset    offset
0       1:         16.03.'04 01:43:02  01:43:15
1       2:         16.03.'04 07:19:36  07:20:21
2       3:         16.03.'04 11:53:54  11:54:02
3       4:         16.03.'04 12:38:16  12:38:23
4       5:         16.03.'04 18:27:12  18:27:43
5       6:         17.03.'04 02:56:20  02:56:30
6       7:         17.03.'04 04:30:15  04:30:30
7       8:         17.03.'04 06:23:41  06:24:06
8       9:         17.03.'04 12:11:02  12:11:44
9      10:         17.03.'04 12:30:10  12:31:03
10     11:         17.03.'04 12:39:06  12:39:10
11     12:         17.03.'04 19:27:04  19:27:23
12     13:         18.03.'04 00:57:14  00:57:34
13     14:         18.03.'04 01:52:51  01:53:05
14     15:         18.03.'04 02:23:49  02:24:14
15     16:         18.03.'04 04:13:08  04:13:29
16     17:         18.03.'04 12:07:43  12:08:17
17     18:         18.03.'04 13:55:08  13:56:02
18     19:         18.03.'04 14:25:01  14:25:15
19     20:         18.03.'04 15:21:24  15:21:35
20     21:         18.03.'04 15:21:58  15:22:10
21     22:         18.03.'04 16:16:00  16:16:19
22     23:         18.03.'04 16:40:50  16:41:17
23     24:         18.03.'04 16:49:45  16:50:18
24     25:         18.03.'04 16:55:18  16:55:34
25     26:         18.03.'04 21:08:19  21:08:32
26     27:         18.03.'04 21:17:24  21:17:40
27     28:         18.03.'04 23:02:59  23:03:49
28     29:         19.03.'04 05:51:23  05:51:45
29     30:         19.03.'04 06:09:44  06:09:57
..     ...                        ...       ...
42     43:         20.03.'04 07:51:21  07:52:40
43     44:         20.03.'04 12:38:02  12:39:19
44     45:         21.03.'04 06:51:17  06:52:08
45     46:         21.03.'04 10:47:42  10:48:18
46     47:         21.03.'04 11:33:28  11:33:54
47     48:         21.03.'04 11:53:48  11:54:06
48     49:         21.03.'04 12:41:06  12:41:31
49     50:         21.03.'04 12:45:07  12:45:47
50     51:         21.03.'04 14:26:57  14:28:00
51     52:         21.03.'04 18:39:26  18:39:58
52     53:         21.03.'04 19:04:25  19:04:47
53     54:         21.03.'04 19:31:35  19:32:17
54     55:         22.03.'04 06:08:12  06:09:04
55     56:         22.03.'04 20:31:17  20:32:00
56     57:         23.03.'04 12:33:10  12:33:22
57     58:         24.03.'04 06:51:25  06:51:52
58     59:         24.03.'04 13:24:23  13:25:19
59     60:         24.03.'04 13:36:09  13:36:14
60     61:         24.03.'04 15:42:24  15:42:39
61     62:         24.03.'04 16:29:43  16:30:00
62     63:         24.03.'04 21:16:55  21:17:15
63     64:         25.03.'04 01:51:01  01:51:25
64     65:         25.03.'04 07:08:41  07:09:28
65     66:         25.03.'04 19:27:07  19:27:40
66     67:         26.03.'04 09:12:19  09:12:36
67     68:         26.03.'04 09:31:35  09:32:30
68     69:         26.03.'04 09:33:24  09:33:32
69     70:         26.03.'04 10:30:08  10:30:36
70     71:         26.03.'04 15:07:51  15:08:27
71  total:  71 subclinical seizure(s)       NaN

[72 rows x 3 columns]

In [28]:
# No weights
n=100
pptn_hit=.3
x=np.ones((n,1))
y=np.zeros(n)
y[:int(np.round(n*pptn_hit))]=1

lr=linear_model.LogisticRegression()
lr.fit(x,y)
# yhat=lr.predict_proba(x)
yhat=lr.predict_proba(x)
print('Ideal %f %f' % ((1-pptn_hit),pptn_hit))
print('Actual {}'.format(yhat[0,:]))

Ideal 0.700000 0.300000
Actual [ 0.69586165  0.30413835]

In [37]:
# YES weights
n=100
pptn_hit=.3
n_hit=int(np.round(n*pptn_hit))
x=np.ones((n,1))
y=np.zeros(n)
y[:n_hit]=1
wts=np.ones(n)
wts[:n_hit]=.5/n_hit
wts[n_hit:]=.5/(n-n_hit)
wts=wts*100

lr=linear_model.LogisticRegression()
lr.fit(x,y,sample_weight=wts)
# yhat=lr.predict_proba(x)
yhat=lr.predict_proba(x)
print(wts[0])
print('sum wts={}'.format(np.sum(wts)))
print('No weighted %f %f' % ((1-pptn_hit),pptn_hit))
print('Ideal is 0.5 0.5')
print('Actual {}'.format(yhat[0,:]))

1.66666666667
sum wts=99.99999999999994
No weighted 0.700000 0.300000
Ideal is 0.5 0.5
Actual [ 0.5  0.5]

In [20]:
lr.predict?

In [29]:
lr.fit?